"""
Interfaces (puertos) de repositorio del dominio.

La capa de aplicación depende de estas abstracciones, no de SQLAlchemy.
Las implementaciones concretas viven en `infrastructure/repositories`.
Esto materializa la Inversión de Dependencias (la D de SOLID).
"""
from __future__ import annotations

import uuid
from typing import Generic, Protocol, TypeVar

T = TypeVar("T")


class Repository(Protocol, Generic[T]):
    async def get(self, entity_id: uuid.UUID) -> T | None: ...
    async def add(self, entity: T) -> T: ...
    async def delete(self, entity: T) -> None: ...
    async def list(self, *, limit: int = 50, offset: int = 0) -> list[T]: ...


class UserRepositoryPort(Protocol):
    async def get(self, user_id: uuid.UUID): ...
    async def get_by_email(self, email: str): ...
    async def add(self, user): ...


class MemorialRepositoryPort(Protocol):
    async def get(self, memorial_id: uuid.UUID): ...
    async def get_by_slug(self, slug: str): ...
    async def add(self, memorial): ...
